In [7]:
import hist
import boost_histogram as bh
import numpy as np
import functools
import operator

In [8]:
h = hist.Hist(
    hist.axis.Regular(bins=10, start=0, stop=10, name="x"),
    hist.axis.Regular(bins=10, start=0, stop=10, name="y"),
    hist.axis.StrCategory(["allTracksters", "mainTrackster"], name="mainOrAllTracksters")
)
h.fill(x=[1, 3, 1, 6], y=[3, 8, 4, 8], mainOrAllTracksters=["allTracksters", "mainTrackster", "mainTrackster", "mainTrackster"])

Hist(
  Regular(10, 0, 10, name='x'),
  Regular(10, 0, 10, name='y'),
  StrCategory(['allTracksters', 'mainTrackster'], name='mainOrAllTracksters'),
  storage=Double()) # Sum: 4.0

In [9]:
h[{"y":slice(hist.loc(1), hist.loc(9), sum), "mainOrAllTracksters":hist.loc("mainTrackster")}]

Hist(Regular(10, 0, 10, name='x'), storage=Double()) # Sum: 3.0

In [10]:
cluster2D_rho_axis = hist.axis.Regular(bins=100, start=0, stop=20., name="clus2D_rho", label="2D cluster rho (local energy density)", transform=hist.axis.transform.sqrt)

In [11]:
h = hist.Hist(cluster2D_rho_axis)
h.fill([3.587443,  0.105543,7.573667,16.626007,0.150658,26.937487,0.099589,41.380047,0.063965,0.125424])

Hist(Regular(100, 0, 20, transform=sqrt, name='clus2D_rho', label='2D cluster rho (local energy density)'), storage=Double()) # Sum: 8.0 (10.0 with flow)

In [12]:
h = hist.Hist(hist.axis.Integer(start=0, stop=10, name="x"))
h.fill([0, 1, 1, 5, 15, 20])
h

Hist(Integer(0, 10, name='x'), storage=Double()) # Sum: 4.0 (6.0 with flow)

In [13]:
h[{"x":slice(hist.loc(3), None, sum)}]
h.axes[0].edges[:-1]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
beamEnergiesAxis = hist.axis.IntCategory([20, 50, 80, 100, 120, 150, 200, 250, 300], name="beamEnergy", label="Beam energy (GeV)")

In [15]:
issubclass(type(beamEnergiesAxis), bh.axis.IntCategory)

True

In [16]:
beamEnergiesAxis.size

9

In [17]:
h = hist.Hist(
    hist.axis.Regular(bins=10, start=0, stop=10, name="x"),
    beamEnergiesAxis
)
h.fill(x=[0, 0, 1, 3, 1, 6, 3, 8, 4, 8], beamEnergy=20)

Hist(
  Regular(10, 0, 10, name='x'),
  IntCategory([20, 50, 80, 100, 120, 150, 200, 250, 300], name='beamEnergy', label='Beam energy (GeV)'),
  storage=Double()) # Sum: 10.0

In [18]:
h[{"beamEnergy":hist.loc(50)}]

Hist(Regular(10, 0, 10, name='x'), storage=Double())

In [19]:
h = hist.Hist(
    hist.axis.Regular(bins=20, start=0, stop=10, name="x"),
    beamEnergiesAxis,
    storage=hist.storage.Weight()
)
h.fill(x=[0, 0, 1, 3, 1, 6, 3, 8, 4, 8], beamEnergy=20, weight=[1, 2, 1, 3, 1, 6, 3, 8, 4, 1])
h.fill(x=[5, 2, 1, 3, 1, 3, 3, 8, 4], beamEnergy=80, weight=[2, 1, 3, 1, 6, 3, 8, 4, 1])

Hist(
  Regular(20, 0, 10, name='x'),
  IntCategory([20, 50, 80, 100, 120, 150, 200, 250, 300], name='beamEnergy', label='Beam energy (GeV)'),
  storage=Weight()) # Sum: WeightedSum(value=59, variance=283)

In [20]:
total = np.sum(h.values()) * functools.reduce(operator.mul, h.axes.widths)
total
h.values() / np.where(total > 0, total, 1)


array([[0.10169492, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.06779661, 0.        , 0.30508475, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.03389831, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.20338983, 0.        , 0.40677966, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],


In [21]:
h3 = hist.Hist(
    hist.axis.Regular(name="x", bins=2, start=0, stop=2),
    hist.axis.Variable([0, .1, 1], name="y")
)
h3.fill(x=[0, 0.8, 1, 1], y=[0, 0.05, 0.9, 0.9])

Hist(
  Regular(2, 0, 2, name='x'),
  Variable([0, 0.1, 1], name='y'),
  storage=Double()) # Sum: 4.0

In [22]:
h3.density()

array([[5.        , 0.        ],
       [0.        , 0.55555556]])

In [23]:
hist.axis.Variable([1, 2, 3, 4, 5, 5.5, 6], name="z").widths

array([1. , 1. , 1. , 1. , 0.5, 0.5])

In [42]:
from bokeh.plotting import figure, show
import bokeh.models
import bokeh
bokeh.io.output_notebook()

Loading BokehJS ...

In [48]:
h = hist.Hist(
    hist.axis.Regular(bins=2, start=0, stop=15, name="x"),
    hist.axis.Regular(bins=3, start=0, stop=10, name="y"),
)
h.fill(x=[1, 3, 1, 6, 9, 1, 4], y=[3, 8, 4, 8, 7, 2, 1],)
h

Hist(
  Regular(2, 0, 15, name='x'),
  Regular(3, 0, 10, name='y'),
  storage=Double()) # Sum: 7.0

In [49]:
f = figure()
axes = h.axes
f.image(image=[np.transpose(h.values())], x=axes[0].edges[0], y=axes[1].edges[0],
            dw=axes[0].edges[-1]-axes[0].edges[0], dh=axes[1].edges[-1]-axes[1].edges[0], 
            #color_mapper=bokeh.models.LinearColorMapper(palette="Spectral11")
            )
show(f)

In [41]:
np.transpose(h.values())

array([[1., 0.],
       [1., 0.],
       [2., 0.]])